export const ACCOUNT_API = '/api/accounts'
export const TOKEN_API = '/token'
export const EXAM_API = '/api/exams'
export const PHOTO_API = 'api/photos'
export const VIDEO_API = 'api/videos'
export const FILE_API = 'api/files'
